"""initial_control_plane

Revision ID: 0001
Revises:
Create Date: 2026-07-11 06:24:27.398918
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=63), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "api_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("token_digest", sa.String(length=64), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_digest"),
    )
    op.create_index("ix_api_credentials_tenant", "api_credentials", ["tenant_id"], unique=False)
    op.create_table(
        "deletion_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "resource_type",
            sa.Enum(
                "song",
                "phrase_audio",
                name="deletionresource",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "completed",
                "failed",
                name="deletionstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_deletion_tenant_identity"),
        sa.UniqueConstraint(
            "tenant_id", "resource_type", "resource_id", name="uq_deletion_resource"
        ),
    )
    op.create_index(
        "ix_deletions_tenant", "deletion_requests", ["tenant_id", "requested_at"], unique=False
    )
    op.create_table(
        "songs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=300), nullable=True),
        sa.Column("rights_basis", sa.String(length=500), nullable=True),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("source_byte_length", sa.Integer(), nullable=True),
        sa.Column("source_media_type", sa.String(length=80), nullable=True),
        sa.Column("source_object_key", sa.String(length=600), nullable=True),
        sa.Column("source_uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "pending_upload",
                "uploaded",
                "processing",
                "accepted",
                "practice_only",
                "rejected",
                "deleted",
                name="songstate",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("manifest_payload", sa.JSON(), nullable=True),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_song_tenant_identity"),
        sa.UniqueConstraint("tenant_id", "source_sha256", name="uq_song_tenant_source"),
    )
    op.create_index("ix_songs_tenant_state", "songs", ["tenant_id", "state"], unique=False)
    op.create_table(
        "deletion_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("object_key", sa.String(length=600), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "completed",
                "failed",
                name="deletionstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id", "request_id"],
            ["deletion_requests.tenant_id", "deletion_requests.id"],
            name="fk_deletion_task_tenant_request",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_deletion_tasks_status", "deletion_tasks", ["status", "next_attempt_at"], unique=False
    )
    op.create_table(
        "song_manifest_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("song_id", sa.Uuid(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("payload_sha256", sa.String(length=64), nullable=True),
        sa.Column("pipeline_version", sa.String(length=128), nullable=False),
        sa.Column("model_release", sa.String(length=128), nullable=False),
        sa.Column("score_version", sa.String(length=128), nullable=False),
        sa.Column("calibration_version", sa.String(length=128), nullable=False),
        sa.Column("produced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id", "song_id"],
            ["songs.tenant_id", "songs.id"],
            name="fk_manifest_tenant_song",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "song_id", "id", name="uq_manifest_tenant_song_identity"),
        sa.UniqueConstraint("tenant_id", "song_id", "payload_sha256", name="uq_manifest_payload"),
    )
    op.create_index(
        "ix_manifests_tenant_song",
        "song_manifest_records",
        ["tenant_id", "song_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "stored_assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("song_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("object_key", sa.String(length=600), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("byte_length", sa.Integer(), nullable=True),
        sa.Column("media_type", sa.String(length=100), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "stored",
                "deleted",
                name="audiostate",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("model_release", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id", "song_id"], ["songs.tenant_id", "songs.id"], name="fk_asset_tenant_song"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "object_key", name="uq_asset_tenant_key"),
    )
    op.create_index(
        "ix_assets_tenant_song", "stored_assets", ["tenant_id", "song_id"], unique=False
    )
    op.create_table(
        "practice_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("song_id", sa.Uuid(), nullable=False),
        sa.Column("manifest_record_id", sa.Uuid(), nullable=False),
        sa.Column("calibration_version", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id", "song_id", "manifest_record_id"],
            [
                "song_manifest_records.tenant_id",
                "song_manifest_records.song_id",
                "song_manifest_records.id",
            ],
            name="fk_session_tenant_song_manifest",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "song_id"], ["songs.tenant_id", "songs.id"], name="fk_session_tenant_song"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "song_id", "id", name="uq_session_tenant_song_identity"),
    )
    op.create_index(
        "ix_sessions_tenant_song", "practice_sessions", ["tenant_id", "song_id"], unique=False
    )
    op.create_table(
        "phrase_artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("song_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("sample_start", sa.Integer(), nullable=False),
        sa.Column("sample_end", sa.Integer(), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=False),
        sa.Column("codec", sa.String(length=20), nullable=False),
        sa.Column("byte_length", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("calibration_version", sa.String(length=128), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column(
            "audio_state",
            sa.Enum(
                "pending",
                "stored",
                "deleted",
                name="audiostate",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("object_key", sa.String(length=600), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("audio_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id", "song_id", "session_id"],
            ["practice_sessions.tenant_id", "practice_sessions.song_id", "practice_sessions.id"],
            name="fk_phrase_tenant_song_session",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_phrase_tenant_idempotency"),
        sa.UniqueConstraint(
            "tenant_id", "session_id", "id", name="uq_phrase_tenant_session_identity"
        ),
        sa.UniqueConstraint("tenant_id", "session_id", "sequence", name="uq_phrase_sequence"),
    )
    op.create_index(
        "ix_phrases_expiry", "phrase_artifacts", ["audio_state", "expires_at"], unique=False
    )
    op.create_index(
        "ix_phrases_tenant_session", "phrase_artifacts", ["tenant_id", "session_id"], unique=False
    )
    op.create_table(
        "score_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("song_id", sa.Uuid(), nullable=False),
        sa.Column("manifest_record_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("phrase_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("schema_version", sa.String(length=40), nullable=False),
        sa.Column("score_version", sa.String(length=128), nullable=False),
        sa.Column("pipeline_version", sa.String(length=128), nullable=False),
        sa.Column("model_release", sa.String(length=128), nullable=False),
        sa.Column("calibration_version", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("payload_sha256", sa.String(length=64), nullable=True),
        sa.Column("produced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id", "session_id", "phrase_id"],
            ["phrase_artifacts.tenant_id", "phrase_artifacts.session_id", "phrase_artifacts.id"],
            name="fk_score_tenant_session_phrase",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "song_id", "manifest_record_id"],
            [
                "song_manifest_records.tenant_id",
                "song_manifest_records.song_id",
                "song_manifest_records.id",
            ],
            name="fk_score_tenant_song_manifest",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "song_id", "session_id"],
            ["practice_sessions.tenant_id", "practice_sessions.song_id", "practice_sessions.id"],
            name="fk_score_tenant_song_session",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_score_tenant_idempotency"),
    )
    op.create_index(
        "ix_scores_tenant_session", "score_records", ["tenant_id", "session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_scores_tenant_session", table_name="score_records")
    op.drop_table("score_records")
    op.drop_index("ix_phrases_tenant_session", table_name="phrase_artifacts")
    op.drop_index("ix_phrases_expiry", table_name="phrase_artifacts")
    op.drop_table("phrase_artifacts")
    op.drop_index("ix_sessions_tenant_song", table_name="practice_sessions")
    op.drop_table("practice_sessions")
    op.drop_index("ix_assets_tenant_song", table_name="stored_assets")
    op.drop_table("stored_assets")
    op.drop_index("ix_manifests_tenant_song", table_name="song_manifest_records")
    op.drop_table("song_manifest_records")
    op.drop_index("ix_deletion_tasks_status", table_name="deletion_tasks")
    op.drop_table("deletion_tasks")
    op.drop_index("ix_songs_tenant_state", table_name="songs")
    op.drop_table("songs")
    op.drop_index("ix_deletions_tenant", table_name="deletion_requests")
    op.drop_table("deletion_requests")
    op.drop_index("ix_api_credentials_tenant", table_name="api_credentials")
    op.drop_table("api_credentials")
    op.drop_table("tenants")
    # ### end Alembic commands ###
